# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tts.text2speech_pb2 as text2speech__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in text2speech_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Text2SpeechServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Text2Speech = channel.unary_unary(
                '/text2speech.Text2SpeechService/Text2Speech',
                request_serializer=text2speech__pb2.Text2SpeechRequest.SerializeToString,
                response_deserializer=text2speech__pb2.Text2SpeechResponse.FromString,
                _registered_method=True)


class Text2SpeechServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Text2Speech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Text2SpeechServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Text2Speech': grpc.unary_unary_rpc_method_handler(
                    servicer.Text2Speech,
                    request_deserializer=text2speech__pb2.Text2SpeechRequest.FromString,
                    response_serializer=text2speech__pb2.Text2SpeechResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'text2speech.Text2SpeechService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('text2speech.Text2SpeechService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Text2SpeechService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Text2Speech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/text2speech.Text2SpeechService/Text2Speech',
            text2speech__pb2.Text2SpeechRequest.SerializeToString,
            text2speech__pb2.Text2SpeechResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
